// <auto-generated />
using System;
using BibliotecaUNAPEC_Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaUNAPEC_Web.Migrations
{
    [DbContext(typeof(BibliotecaUnapecContext))]
    partial class BibliotecaUnapecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Autore", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAutor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAutor")
                        .HasName("PK__Autores__9AE8206A6D278F2F");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Ciencia", b =>
                {
                    b.Property<int>("IdCiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCiencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiencia"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdCiencia")
                        .HasName("PK__Ciencias__2F70679BCA1A095F");

                    b.ToTable("Ciencias");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Editoriale", b =>
                {
                    b.Property<int>("IdEditorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEditorial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditorial"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pais");

                    b.HasKey("IdEditorial")
                        .HasName("PK__Editoria__9DF182DBE1AD9552");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEmpleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cedula");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fechaIngreso");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TandaLaboral")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tandaLaboral");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__Empleado__5295297C12C8C02B");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Idioma", b =>
                {
                    b.Property<int>("IdIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idIdioma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIdioma"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdIdioma")
                        .HasName("PK__Idiomas__A96571FCD03C47E5");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLibro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<string>("AnioPublicacion")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("anioPublicacion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("idAutor");

                    b.Property<int?>("IdCiencia")
                        .HasColumnType("int")
                        .HasColumnName("idCiencia");

                    b.Property<int?>("IdEditorial")
                        .HasColumnType("int")
                        .HasColumnName("idEditorial");

                    b.Property<int?>("IdIdioma")
                        .HasColumnType("int")
                        .HasColumnName("idIdioma");

                    b.Property<int?>("IdTipoBibliografia")
                        .HasColumnType("int")
                        .HasColumnName("idTipoBibliografia");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("IdLibro")
                        .HasName("PK__Libros__5BC0F0262BDCF95E");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdCiencia");

                    b.HasIndex("IdEditorial");

                    b.HasIndex("IdIdioma");

                    b.HasIndex("IdTipoBibliografia");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.PrestamosDevolucione", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTransaccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<int?>("CantidadDias")
                        .HasColumnType("int")
                        .HasColumnName("cantidadDias");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentario");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaDevolucion")
                        .HasColumnType("date")
                        .HasColumnName("fechaDevolucion");

                    b.Property<DateOnly?>("FechaPrestamo")
                        .HasColumnType("date")
                        .HasColumnName("fechaPrestamo");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("idEmpleado");

                    b.Property<int?>("IdLibro")
                        .HasColumnType("int")
                        .HasColumnName("idLibro");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<decimal?>("MontoPorDia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("montoPorDia");

                    b.HasKey("IdTransaccion")
                        .HasName("PK__Prestamo__5B8761F07EF3057A");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdLibro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Prestamos_Devoluciones", (string)null);
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.TiposBibliografium", b =>
                {
                    b.Property<int>("IdTipoBibliografia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoBibliografia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoBibliografia"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdTipoBibliografia")
                        .HasName("PK__TiposBib__8B2D2ADFD6B3C460");

                    b.ToTable("TiposBibliografia");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cedula");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("NoCarnet")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("noCarnet");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoPersona")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipoPersona");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__645723A6EB9E8935");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Libro", b =>
                {
                    b.HasOne("BibliotecaUNAPEC_Web.Models.Autore", "IdAutorNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdAutor")
                        .HasConstraintName("FK__Libros__idAutor__31EC6D26");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.Ciencia", "IdCienciaNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdCiencia")
                        .HasConstraintName("FK__Libros__idCienci__33D4B598");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.Editoriale", "IdEditorialNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdEditorial")
                        .HasConstraintName("FK__Libros__idEditor__32E0915F");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.Idioma", "IdIdiomaNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdIdioma")
                        .HasConstraintName("FK__Libros__idIdioma__34C8D9D1");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.TiposBibliografium", "IdTipoBibliografiaNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdTipoBibliografia")
                        .HasConstraintName("FK__Libros__idTipoBi__35BCFE0A");

                    b.Navigation("IdAutorNavigation");

                    b.Navigation("IdCienciaNavigation");

                    b.Navigation("IdEditorialNavigation");

                    b.Navigation("IdIdiomaNavigation");

                    b.Navigation("IdTipoBibliografiaNavigation");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.PrestamosDevolucione", b =>
                {
                    b.HasOne("BibliotecaUNAPEC_Web.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("PrestamosDevoluciones")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK__Prestamos__idEmp__38996AB5");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.Libro", "IdLibroNavigation")
                        .WithMany("PrestamosDevoluciones")
                        .HasForeignKey("IdLibro")
                        .HasConstraintName("FK__Prestamos__idLib__398D8EEE");

                    b.HasOne("BibliotecaUNAPEC_Web.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("PrestamosDevoluciones")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Prestamos__idUsu__3A81B327");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdLibroNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Autore", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Ciencia", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Editoriale", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Empleado", b =>
                {
                    b.Navigation("PrestamosDevoluciones");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Idioma", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Libro", b =>
                {
                    b.Navigation("PrestamosDevoluciones");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.TiposBibliografium", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaUNAPEC_Web.Models.Usuario", b =>
                {
                    b.Navigation("PrestamosDevoluciones");
                });
#pragma warning restore 612, 618
        }
    }
}
